name: 'CSAT survey for ADK-Java'
on:
  issues:
    types:
      - closed

permissions:
  contents: read
  issues: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/csat.js')
            script({github, context})
            